name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [alpha, beta, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
          cd ${{ matrix.environment }}
          terraform init

      - name: Terraform Plan
        run: |
          cd ${{ matrix.environment }}
          terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan-${{ matrix.environment }}
          path: ${{ matrix.environment }}/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: plan
    strategy:
      matrix:
        environment: [alpha, beta, prod]
    if: matrix.environment != 'prod' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan-${{ matrix.environment }}
          path: ${{ matrix.environment }}

      - name: Terraform Apply
        run: |
          cd ${{ matrix.environment }}
          terraform apply -auto-approve tfplan

      - name: Run Automation Script on Target Resources
        run: |
          cd scripts
          ./configure_resources.sh ${{ matrix.environment }}
        env:
          ENVIRONMENT: ${{ matrix.environment }}
        shell: bash
      # The configure_resources.sh script should be set to executable in the repo and can take environment parameters to configure different setups.

  pro_ti_tests:
    runs-on: ubuntu-latest
    needs: apply
    strategy:
      matrix:
        environment: [alpha, beta, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ProTI Tests
        run: |
          cd ${{ matrix.environment }}/test
          go test -v

      - name: Run Additional Automation Script for Testing
        run: |
          cd scripts
          ./run_tests.sh ${{ matrix.environment }}
        shell: bash
